# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe669ad1b432187beb63a3bb5d4a8761d2ff78ad6000b7d80679fe578a9a013ccc185d27fa4c5b2f137a975863f2e7d8ff6def13fe772cc7bb6c594340f39512

test:
  secret_key_base: e3b386a71b6941190448d88ef5b09123be9638f802f592a677798caac1b8a5d9282826807160ec0370e9a23e1a4fe0174d8233067ef312b79e809f42b7ff8266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
